name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Pytest Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "werkzeug==2.3.7" "Flask>=2.2.5,<3.0.0"
          pip install -r requirements.txt

      - name: Debug Python Environment
        run: |
          python --version
          pip freeze

      - name: Run Tests
        run: pytest -v --tb=short test_app.py

  docker-build-and-test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t flask_app .

      - name: Run Docker Container
        run: |
          docker run -d -p 5050:5050 --name flask_app flask_app
          sleep 5  # Wait for container to start

      - name: Test Running Container
        run: |
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:5050 || exit 1

      - name: Stop and Remove Container
        run: |
          docker stop flask_app
          docker rm flask_app
